import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { dark } from "@clerk/themes";

import { ToastContainer, Slide } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { ClerkProvider } from "@clerk/nextjs";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Room",
	description: "Generated by room dev",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<ClerkProvider
				appearance={{
					baseTheme: dark,
					variables: {
						colorPrimary: "#131315",
					},
				}}
			>
				<body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black text-black`}>
					{children}
					<ToastContainer
						position='top-center'
						autoClose={4000}
						limit={1}
						hideProgressBar={false}
						newestOnTop={false}
						closeOnClick={false}
						rtl={false}
						pauseOnFocusLoss={false}
						draggable={false}
						pauseOnHover
						theme='dark'
						transition={Slide}
					/>
				</body>
			</ClerkProvider>
		</html>
	);
}
